### ISSUE TITLE
Maybe a typo in solutions for Analytical Exercise 1.1 in W1D2_Tutorial2

### ISSUE THREAD

**Issue by HaiyangJin** [NeuromatchAcademy/course-content-dl#176]
For Analytical Exercise 1.1: Loss Gradients (W1D2_Tutorial2):

The current solution is:
∂𝑙𝑜𝑠𝑠/∂𝑤_1 = 2 𝑤_2⋅𝑥⋅(𝑦−𝑤_1⋅𝑤_2⋅𝑥)
∂𝑙𝑜𝑠𝑠/∂𝑤_2 = 2 𝑤_1⋅𝑥⋅(𝑦−𝑤_1⋅𝑤_2⋅𝑥)

It seems that the solution should be:
∂𝑙𝑜𝑠𝑠/∂𝑤_1 = **-** 2 𝑤_2⋅𝑥⋅(𝑦−𝑤_1⋅𝑤_2⋅𝑥)
∂𝑙𝑜𝑠𝑠/∂𝑤_2 = **-** 2 𝑤_1⋅𝑥⋅(𝑦−𝑤_1⋅𝑤_2⋅𝑥)

(which also matches the solution provided for `dloss_dw()` in `ShallowNarrowExercise()`; coding exercise 1.1)

**Comment by spirosChv** [comment]
Thank you very much for the catch and report. We have updated the code with the correct answer, indeed a minus sign was missing.

https://github.com/NeuromatchAcademy/course-content-dl/pull/180/files#diff-f4557b153424160c9a9086bba6ab039799ff6989bb78533c7eb5bf1b8243b4eaL758-R762
