### ISSUE TITLE
W1D3 and W1D3_Tutorial1

### ISSUE THREAD

**Issue by HaiyangJin** [NeuromatchAcademy/course-content-dl#193]
In the [tutorial](https://github.com/NeuromatchAcademy/course-content-dl/tree/main/tutorials) page, the YouTube Playlist for W1D3 links to the playlist for W1D1 (instead of W1D3). 

In W1D3_Tutorial1:
Video 3: Build MLP is not set up properly. It seems that the video id is missing: 
`video = YouTubeVideo(id=f"", width=854, height=480, fs=1, rel=0)`
(Never mind if the video is not ready. But it seems all other videos are set properly, at least for Youtube)

**Comment by spirosChv** [comment]
> In the [tutorial](https://github.com/NeuromatchAcademy/course-content-dl/tree/main/tutorials) page, the YouTube Playlist for W1D3 links to the playlist for W1D1 (instead of W1D3).
> 
> In W1D3_Tutorial1:
> Video 3: Build MLP is not set up properly. It seems that the video id is missing:
> `video = YouTubeVideo(id=f"", width=854, height=480, fs=1, rel=0)`
> (Never mind if the video is not ready. But it seems all other videos are set properly, at least for Youtube)

The playlist was wrongly set up, thanks for the catch. Some videos in specific tutorials are missing. We will update them as soon as they are ready.

**Comment by HaiyangJin** [comment]
Thanks for the clarification. 

(Not sure if I should open a new issue but the followings are also for W1D3_Tutorial 1)
It seems that the video for "Video 5: Train Test" has not been set properly. 

Maybe some codes can be removed:
Just below the "Think! 3.3.1" title, "Now let's put everything together and train your first deep-ish model!"
The codes between Line 9 and Line 20 seem to be redundant. They are not used later and are also duplicated with codes in a previous chunk (after the text "Use a Dataloader that will actually read the data in batches ..."). 

BTW, I really enjoy all the materials!

**Comment by spirosChv** [comment]
Two missing videos were added.

Yes, the code lines 9-20 are not used. So, I removed it.
