### ISSUE TITLE
W1D5_Tutorial2 Dropout

### ISSUE THREAD

**Issue by HaiyangJin** [NeuromatchAcademy/course-content-dl#228]
(Just before Section 2.1) The notebook tries to compare the results of models with and without dropout and the results (losses) are quite similar (I guess they are supposed to be different?)

It seems that both the losses for the model with dropout (`test_loss_dp`; in the section above "Animation! (Run Me!)") and losses for the model without dropout (`test_loss`; in the "Run to train the default network" section) are obtained from the `Net()` model, in which the Dropout is applied. 

Maybe the model used in the 'Run to train the default network' section should be a certain model without Dropout. 

Hope I do not understand the codes incorrectly.

**Comment by spirosChv** [comment]
> (Just before Section 2.1) The notebook tries to compare the results of models with and without dropout and the results (losses) are quite similar (I guess they are supposed to be different?)
> 
> It seems that both the losses for the model with dropout (`test_loss_dp`; in the section above "Animation! (Run Me!)") and losses for the model without dropout (`test_loss`; in the "Run to train the default network" section) are obtained from the `Net()` model, in which the Dropout is applied.
> 
> Maybe the model used in the 'Run to train the default network' section should be a certain model without Dropout.
> 
> Hope I do not understand the codes incorrectly.

Very good catch! I have created a `NetDropout` to calculate `test_loss_dp`, and the simple `Net` to calculate `test_loss`
