### ISSUE TITLE
Coding exercise 2.4 in  W1D1_Tutorial 1_ Student notebook

### ISSUE THREAD

**Issue by tem-ctrl** [NeuromatchAcademy/course-content-dl#356]
In coding exercise 2.4, there are no specifications neither for tensors **x, y, z** nor for expected outcomes.

On the other hand, no  docstring is provided for the helper function **timeFun** so don't know what **f** refers to.

**Comment by spirosChv** [comment]
@tem-ctrl the notebook has been updated yesterday and contains specifications for the `x`, `y`, `and `z` tensors. 

Are you sure that you are using the updated version from Github?

colab:
![image](https://user-images.githubusercontent.com/10776251/127849321-d2f037eb-7737-4579-a5ef-4a27c37add2b.png)

book:
![image](https://user-images.githubusercontent.com/10776251/127849440-0b89f28f-83d7-40aa-bb48-3ac720c7492d.png)

**Comment by tem-ctrl** [comment]
Ok thanks.
Sorry
