### ISSUE TITLE
A very long logging outputs scroll in the human_rl notebook

### ISSUE THREAD

**Issue by morteza** [NeuromatchAcademy/course-content-dl#404]
The [run the loop section](https://deeplearning.neuromatch.io/projects/ReinforcementLearning/human_rl.html#run-the-loop
) in the human_rl notebook produces a very large piece of output, making the rest of the notebook difficult to reach due to the scrolling.

Either discarding the outputs or setting the `n_episodes=10` would resolve the issue (it's in the second line of the cell below the section title).

**Comment by spirosChv** [comment]
fixed by adding IPython.display clear_output call before the last print. Pushing, merging, and closing the issue. Changes will be reflected in the book after 30 mins.
