### ISSUE TITLE
typos in Section 1.3: L2 / Ridge Regularization in W1D5_Tutorial2

### ISSUE THREAD

**Issue by yasutak** [NeuromatchAcademy/course-content-dl#423]
The formulas for the derivative of LR and update rule might have some typos.

The correct formulas should be

\frac{\partial L_r}{\partial w^{(r)}_{ij}}=\frac{\partial L}{\partial w^{(r)}_{ij}} + 2\lambda w^{(r)}_{ij} 
(add 2 in front of the last term and remove 'cdot')

w^{(r)}_{ij}←w^{(r)}_{ij}−η\frac{\partial L}{\partial W^{(r)}_{ij}}−2 \eta \lambda w^{(r)}_{ij}=(1−2 \eta \lambda)w^{(r)}_{ij} − \eta \frac{\partial L}{\partial w^{(r)}_{ij}}
(reflect the above correction)

**Comment by spirosChv** [comment]
Thank you very much for letting us know! We have fixed that and the updated code is currently running through our process. So, it will be merged on main in a couple of minutes.
