### ISSUE TITLE
W1D5, tutorial #2, Think 3.1 and Think! 5

### ISSUE THREAD

**Issue by EitanHemed** [NeuromatchAcademy/course-content-dl#429]
**Problem description**
Accessing this [notebook](https://deeplearning.neuromatch.io/tutorials/W1D5_Regularization/student/W1D5_Tutorial2.html), 
submitting the answer on _Think! 3.1_ and _Think! 5_ results in `NameError: name 'q1' is not defined`.

**Suggested solution**
Change `def_button_clicked` current function body into the following:
```
def on_button_clicked(b):
   atform.add_answer('q1', text.value)
   print("Submission successful!")
```

The same solution can be applied to Think! 5, by changing the current function body onto:
```
def on_button_clicked(b):
   atform.add_answer('q2', text.value)
   print("Submission successful!")
``` 

Thanks!

**Comment by spirosChv** [comment]
fixed and merged in `main`
