### ISSUE TITLE
W3D3_Tutorial1: Coding Exercise 5 and Section 5.1

### ISSUE THREAD

**Issue by HaiyangJin** [NeuromatchAcademy/course-content-dl#460]
**W3D3_Tutorial1: Coding Exercise 5**

In the last line (Line 48), the `win_rate_player1` is not calculated based on the `result` in Line 46. `win_rate_player1` still displays the value calculated in Section 3. 

Probably `win_rate_player1 = result[0]/num_games # result[0] is the number of times that player 1 wins` should be added after Line 46.

<br>

**W3D3_Tutorial1: Section 5.1**
The title does not match the two players in the codes. 

According to the title (if I understand correctly), this section would like to compare the sample-based player and the "greedy" player, which duplicates Section 5.3. 
But according to the code, this section compares the sample-based player with a random player. 

Maybe the title for Section 5.1 should be updated to match the codes.

**Comment by HaiyangJin** [comment]
Typos in the expected results for "Monte-Carlo player against Value-based player" and "Monte-Carlo player against Policy-based player" in Section 7. 

The final win rate for player 1 is correct (i.e., 50%). However, there are typos for the number of games won by player1 and player2, which should be 10 for each (now it is 11 and 9 respectively).

**Comment by spirosChv** [comment]
@HaiyangJin thank you very much for catching these errors/typos. I have push a commit (https://github.com/NeuromatchAcademy/course-content-dl/commit/fa2ef0517e02d262b21adb9419a3697d57638d35), but I will merge once GitHub Actions are back on line.
