### ISSUE TITLE
Issue on page /tutorials/W1D4_Optimization/student/W1D4_Tutorial1.html

### ISSUE THREAD

**Issue by JonathanKeefe** [NeuromatchAcademy/course-content-dl#521]
Videos aren't loading in the book! All areas where the youtube video box should appear are empty.

**Comment by JonathanKeefe** [comment]
This seems to be an issue in many if not all of the books after W1D4

**Comment by spirosChv** [comment]
@JonathanKeefe this is a known issue that we will try to resolve. See here: https://github.com/NeuromatchAcademy/course-content-dl/issues/418

Thank you for reporting it.
