### ISSUE TITLE
Issue on page /tutorials/W1D2_LinearDeepLearning/student/W1D2_Tutorial1.html

### ISSUE THREAD

**Issue by SubaruSpirit** [NeuromatchAcademy/course-content-dl#526]
In Section 3, Loss function - The loss that we are going to be optimizing, which is often combined with regularization terms (`conming` up in few days).

Should be `coming`

**Comment by spirosChv** [comment]
fixed in https://github.com/NeuromatchAcademy/course-content-dl/pull/531
