### ISSUE TITLE
W2D3_Tutorial2: load IMDB dataset error

### ISSUE THREAD

**Issue by woodwm** [NeuromatchAcademy/course-content-dl#534]
see also: https://deeplearning.neuromatch.io/tutorials/W2D3_ModernRecurrentNeuralNetworks/student/W2D3_Tutorial2.html#section-1-1-load-and-view-of-the-dataset

```sh
IndexError: list index out of range
```

`!pip install torchtext==0.4.0 --quiet` is a quite old version. Many functions are moved to `torchtext.legacy`.

**Comment by spirosChv** [comment]
Thank you @woodwm . I have updated the code respectively.
