### ISSUE TITLE
Access to NMA 2021 

### ISSUE THREAD

**Issue by ldaumail** [NeuromatchAcademy/course-content-dl#634]
I remember for people who subscribed to the course last year, you said that the course would be accessible forever. It seems that it is no longer accessible to me. Was the content from 2021 relocated?

Thank you,
-Loïc

**Comment by spirosChv** [comment]
Hello. The course content of 2021 can be found here: https://github.com/NeuromatchAcademy/course-content-dl/tree/NMADL2021

Best

**Comment by ldaumail** [comment]
Thank you! Is the Google Collab format also available?

Best,
-Loïc

**Comment by spirosChv** [comment]
Yes, for all notebooks: e.g., https://colab.research.google.com/github/NeuromatchAcademy/course-content-dl/blob/NMADL2021/tutorials/W1D1_BasicsAndPytorch/W1D1_Tutorial1.ipynb

Notice that in some notebooks due to updates in some libraries you may need to update also the install dependencies.

**Comment by ldaumail** [comment]
It doesn't seem to work for some tutorials (see screenshot above when I try opening the google collab version

**Comment by spirosChv** [comment]
> It doesn't seem to work for some tutorials (see screenshot above when I try opening the google collab version

See my answer. You use the `main` so obviously, the tutorials are not there, as we have changed the order and we are updating some days according to students' feedback.
