### ISSUE TITLE
Does W2D4_Tutorial4 need ngrok authtoken?

### ISSUE THREAD

**Issue by lanluo9** [NeuromatchAcademy/course-content-dl#705]
Thanks for sharing the course content! I'm going through [W2D4 Tutorial 4: Deploying Neural Networks on the Web](https://github.com/NeuromatchAcademy/course-content-dl/tree/main/tutorials/W2D4_GenerativeModels) using Google Colab, and ran into a problem in Section 2.1:

```
# Create a Flask app object
app = Flask(__name__)

# Define a function to be called when the user accesses the root URL (/)
# Handler
@app.route("/")
def home():
  # Return a very simple HTML response
  return "<h1>Welcome to Neuromatch</h1>"


# You need ngrok to expose the Flask app outside of the notebook
run_with_ngrok(app)

## Uncomment below to run the app
app.run()
```

This cell generates 
` * Running on http://xx-xx-xx.ngrok.io`
which leads to an error page:

![ngrok](https://user-images.githubusercontent.com/51414865/178355425-bd0a2512-80ed-45bc-8839-f89ce3e349c3.png)

Did I miss some step when following this tutorial, or should there be a code cell that imports the ngrok authtoken before running the flask app? Perhaps it can be implemented using [pyngrok](https://towardsdatascience.com/quickly-share-ml-webapps-from-google-colab-using-ngrok-for-free-ae899ca2661a)?

Thanks for your help!

**Comment by spirosChv** [comment]
Thank you for reporting this issue. I will contact the content creators and we will push a fix if needed!

**Comment by lanluo9** [comment]
@spirosChv 
Thanks for fixing the authtoken! I'm going through the updated notebook and noticed that after a few times, launching a new flask app on ngrok will get the user stuck on the ERR_NGROK_6024 page. I've tried using Chrome, Firefox, Edge, and they all get stuck the same way.

![ERR_NGROK_6024](https://user-images.githubusercontent.com/51414865/180841704-ecbf8a1e-5e32-4695-9225-47920d5c2b45.png)

Clicking the "visit site" button doesn't do anything. I also see other people getting stuck on this error page: https://stackoverflow.com/questions/72802372/ngrok-warning-bypass-in-iframe

The error page says that it can be avoided by setting and sending an [ngrok-skip-browser-warning] request header with any value. After some searching I couldn't figure out how to do it; could there be a line of code added above to do that?
