### ISSUE TITLE
Link to Image Alignment has a typo

### ISSUE THREAD

**Issue by rmndrs89** [NeuromatchAcademy/course-content-dl#707]
The hyperlink from that should redirect to the notebook has a typo for the Computer Vision project on Image Alignment. The slide can be found [here](https://deeplearning.neuromatch.io/_images/image_alignment.svg)

Currently it is set as: https://colab.research.google.com/github/NeuromatchAcademy/course-content-dl/blob/main/projects/ComputerVision/Image_Alignment.ipynb

but it should be (according to the corresponding GitHub repo), hence no capital letters for Image and Alignment: https://colab.research.google.com/github/NeuromatchAcademy/course-content-dl/blob/main/projects/ComputerVision/image_alignment.ipynb

**Comment by spirosChv** [comment]
Thank you very much for catching this broken link! We will fix it asap.
