### ISSUE TITLE
W1D3 Coding exercise 2. Wrong argument documentation

### ISSUE THREAD

**Issue by dungscout96** [NeuromatchAcademy/course-content-dl#713]
hidden_unit_nums should be a list of int, not int per function documentation

**Comment by spirosChv** [comment]
Hey @dungscout96 ! In which tutorial does this issue refer? Tutorial 1 or tutorial 2?

**Comment by GaganaB** [comment]
Our latest branch fixes this. Thanks for pointing out this issue @dungscout96. Much appreciated :)
