### ISSUE TITLE
W2D5 - Broken image links

### ISSUE THREAD

**Issue by dungscout96** [NeuromatchAcademy/course-content-dl#739]
Section 2.1 and 2.3 in Tutorial 2 have broken image links

**Comment by GaganaB** [comment]
Hi @dungscout96, 

Can you elaborate on what links in [W2D5T2](https://colab.research.google.com/github/NeuromatchAcademy/course-content-dl/blob/main/tutorials/W2D5_TimeSeriesAndNaturalLanguageProcessing/instructor/W2D5_Tutorial2.ipynb#scrollTo=H0dc8OlaW6NL) are broken? 

Everything seems fine on my end?

Thanks.

**Comment by dungscout96** [comment]
I was looking at the main webpage version: https://deeplearning.neuromatch.io/tutorials/W2D5_TimeSeriesAndNaturalLanguageProcessing/student/W2D5_Tutorial2.html#section-2-1-text-generation-and-language-modelling

**Comment by spirosChv** [comment]
Thank you, @dungscout96, for catching this. We have updated the notebook on GitHub (PR https://github.com/NeuromatchAcademy/course-content-dl/pull/743), and the changes will be reflected on the jupyterbook later on.
