### ISSUE TITLE
Issue on page /tutorials/W2D3_ModernConvnets/student/W2D3_Tutorial1.html

### ISSUE THREAD

**Issue by aritra1705** [NeuromatchAcademy/course-content-dl#748]
The top 5 names provided in the solution given for Coding Exercise 4.1 does not match with the results obtained:

<img width="1073" alt="Screen Shot 2022-07-20 at 2 20 18 AM" src="https://user-images.githubusercontent.com/14016810/179911040-b599ebd2-c90a-4383-af4d-da23cc7295a6.png">

The last two entries are different.

**Comment by GaganaB** [comment]
Hi @aritra1705, 

Thanks for catching this. However, I'm closing this as it's a known issue. See #466
