### ISSUE TITLE
Issue on page /tutorials/W3D1_AttentionAndTransformers/student/W3D1_Tutorial1.html

### ISSUE THREAD

**Issue by johnowhitaker** [NeuromatchAcademy/course-content-dl#771]
Section 9 ('Section 9: Transformers beyond Language models') lists Dalle-2 by OpenAI as an example for artistic use. The original dall-e model was transformer based (as is the derivative dalle-mini) but Dalle 2 uses diffusion models instead. A more appropriate link might be Google's Parti, which does use transformers: https://parti.research.google/

**Comment by GaganaB** [comment]
Hi @johnowhitaker, 

Thank you for pointing this out. The idea was that Dalle-2 uses transformers in the background (decoder for diffusion priors etc). However, Parti does seem like a great addition to the list. We'll consider refining this. Thank you for your suggestion. 

Gagana. :).
