### ISSUE TITLE
W2D2 tutorial1

### ISSUE THREAD

**Issue by wangshaonan** [NeuromatchAcademy/course-content-dl#917]
There might be some error in W2D2's tutorial1, section 3.1 and section 3.2 should be in section 2 because these two talked about kernels instead of pooling. In addition, in the last part of W2D2 tutorial 1, the content should be updated since we no longer talk about RNN. Should modify the following paragraph 'Summary In this Tutorial we have familiarized ouselves with CNNs. We have leaned how the convolution operation works and be applied in various images. Also, we have learned to implement our own CNN. In the next Tutorial, we will go deeper in the training of CNNs!
Next we will talk about RNNs, which shares parameters over time.'

**Comment by spirosChv** [comment]
@wangshaonan I have updated the tile of section 3 to "Kernels, Pooling and Sampsampling". Is a simpler change. Otherwise, the section 2 will be very lengthy!
